name: linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: apt-update
      run: sudo apt-get update
    - name: apt
      run: sudo apt-get install mesa-common-dev libglx-dev libxcursor-dev libxrandr-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libwayland-dev libxkbcommon-dev libgles2-mesa-dev    
    - name: make
      run: cd example && make
